apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openhorizons-dev-secret-store
  labels:
    app.kubernetes.io/part-of: open-horizons-platform
    app.kubernetes.io/name: external-secrets
    open-horizons/horizon: h1
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://kv-sura-dev-mvp.vault.azure.net
      tenantId: 9dbc76ea-fb25-4b07-8f07-5dc315999b76
      serviceAccountRef:
        name: external-secrets-controller
        namespace: external-secrets