apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: backstage
  labels:
    app.kubernetes.io/component: developer-portal
    app.kubernetes.io/instance: sura-ohorizons
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: sura-ohorizons
automountServiceAccountToken: false
