apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{values.name}}-secrets
  namespace: ${{values.namespace}}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openhorizons-dev-secret-store
  target:
    name: ${{values.name}}-secrets
    creationPolicy: Owner
  data:
    - secretKey: AZURE_OPENAI_ENDPOINT
      remoteRef:
        key: ${{values.azureOpenAIEndpointSecretKey}}
    - secretKey: AZURE_OPENAI_API_KEY
      remoteRef:
        key: ${{values.azureOpenAIApiKeySecretKey}}
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: ${{values.githubTokenSecretKey}}
