import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${{ values.appName }}',
  description: 'Generated by Open Horizons Golden Path',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
