apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-dashboards

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
