import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { fetchRaw, listContents, fetchUrl } from "../shared/github-fetcher.js";
import { textResult } from "../shared/types.js";
import { cacheGet, cacheSet } from "../shared/cache.js";

// @backstage/ui — new design system, source in backstage/backstage monorepo
const OWNER = "backstage";
const REPO = "backstage";
const BRANCH = "master";
const UI_BASE = "packages/ui";
const STORYBOOK_INDEX_URL = "https://backstage.io/storybook/index.json";

interface StorybookEntry {
  type: string;
  id: string;
  name: string;
  title: string;
  importPath: string;
  componentPath?: string;
  tags?: string[];
  exportName?: string;
}

async function fetchStorybookIndex(): Promise<Record<string, StorybookEntry>> {
  const cacheKey = "storybook:index";
  const cached = cacheGet(cacheKey);
  if (cached) return JSON.parse(cached);
  const raw = await fetchUrl(STORYBOOK_INDEX_URL);
  const data = JSON.parse(raw) as { entries: Record<string, StorybookEntry> };
  cacheSet(cacheKey, JSON.stringify(data.entries));
  return data.entries;
}

export function registerBackstageUiTools(server: McpServer): void {
  server.tool(
    "backstageui_list_components",
    "List all components in the new Backstage UI design system (@backstage/ui) — sourced from packages/ui/src/components in github.com/backstage/backstage. This is the canonical component library shown at ui.backstage.io.",
    {},
    async () => {
      const items = await listContents(OWNER, REPO, `${UI_BASE}/src/components`, BRANCH);
      const components = items
        .filter((i) => i.type === "dir")
        .map((i) => i.name)
        .sort((a, b) => a.localeCompare(b));
      const lines = [
        `# @backstage/ui — ${components.length} Components`,
        `Source: github.com/${OWNER}/${REPO}/tree/${BRANCH}/${UI_BASE}/src/components`,
        `Reference: https://ui.backstage.io\n`,
        ...components.map((c) => `- ${c}`),
        "\nUse backstageui_get_component to see the API and usage for a specific component.",
      ];
      return textResult(lines.join("\n"));
    }
  );

  server.tool(
    "backstageui_get_component",
    "Get the TypeScript interface, props, and source for a specific @backstage/ui component (e.g. 'Button', 'Card', 'Table', 'Accordion', 'Alert'). Use backstageui_list_components to discover names.",
    {
      component: z
        .string()
        .describe("Component name with correct casing (e.g. 'Button', 'Card', 'Table', 'Accordion')"),
    },
    async ({ component }) => {
      const basePath = `${UI_BASE}/src/components/${component}`;
      const contents: string[] = [
        `# @backstage/ui — ${component}`,
        `Source: github.com/${OWNER}/${REPO}/tree/${BRANCH}/${basePath}\n`,
      ];

      // Try index.tsx (types + exports)
      try {
        const index = await fetchRaw(OWNER, REPO, `${basePath}/index.tsx`, BRANCH);
        contents.push(`## index.tsx\n\`\`\`tsx\n${index}\n\`\`\``);
      } catch {
        // try index.ts
        try {
          const index = await fetchRaw(OWNER, REPO, `${basePath}/index.ts`, BRANCH);
          contents.push(`## index.ts\n\`\`\`ts\n${index}\n\`\`\``);
        } catch {
          /* skip */
        }
      }

      // Try to list files in the component dir
      try {
        const files = await listContents(OWNER, REPO, basePath, BRANCH);
        const tsFiles = files.filter(
          (f) => f.type === "file" && (f.name.endsWith(".tsx") || f.name.endsWith(".ts")) && !f.name.endsWith("stories.tsx") && !f.name.endsWith("test.tsx")
        );
        for (const file of tsFiles.slice(0, 3)) {
          try {
            const src = await fetchRaw(OWNER, REPO, file.path, BRANCH);
            contents.push(`\n## ${file.name}\n\`\`\`tsx\n${src}\n\`\`\``);
          } catch {
            /* skip */
          }
        }
      } catch {
        /* skip */
      }

      if (contents.length === 2) {
        return textResult(
          `Component not found: ${component}\n\nUse backstageui_list_components to see available components.`
        );
      }
      return textResult(contents.join("\n"));
    }
  );

  server.tool(
    "backstageui_get_api_report",
    "Get the full @backstage/ui API report — all exported types, interfaces, functions, and components with their TypeScript signatures. Generated by API Extractor.",
    {},
    async () => {
      const report = await fetchRaw(OWNER, REPO, `${UI_BASE}/report.api.md`, BRANCH);
      return textResult(
        `# @backstage/ui — Full API Report\nSource: github.com/${OWNER}/${REPO}/blob/${BRANCH}/${UI_BASE}/report.api.md\n\n${report}`
      );
    }
  );

  server.tool(
    "backstageui_get_readme",
    "Get the @backstage/ui package README — overview, installation, usage patterns, theming, and design system philosophy.",
    {},
    async () => {
      const readme = await fetchRaw(OWNER, REPO, `${UI_BASE}/README.md`, BRANCH);
      return textResult(
        `# @backstage/ui README\nSource: github.com/${OWNER}/${REPO}/blob/${BRANCH}/${UI_BASE}/README.md\n\n${readme}`
      );
    }
  );

  server.tool(
    "backstageui_get_changelog",
    "Get the @backstage/ui CHANGELOG — version history and recent changes to the Backstage design system.",
    {},
    async () => {
      const changelog = await fetchRaw(OWNER, REPO, `${UI_BASE}/CHANGELOG.md`, BRANCH);
      return textResult(
        `# @backstage/ui CHANGELOG\nSource: github.com/${OWNER}/${REPO}/blob/${BRANCH}/${UI_BASE}/CHANGELOG.md\n\n${changelog}`
      );
    }
  );

  // ── Storybook ─────────────────────────────────────────────────────────────

  server.tool(
    "backstageui_storybook_list_stories",
    "List all 643 stories from backstage.io/storybook — organized by component group. Covers Backstage UI (new design system), Data Display, Feedback, Layout, Navigation, Inputs, Catalog, Search, Home, and Org plugin components. Use backstageui_storybook_get_story to fetch story source code.",
    {
      filter: z
        .string()
        .optional()
        .describe(
          "Optional filter by component name or category (case-insensitive, e.g. 'Button', 'Table', 'Backstage UI', 'Data Display')"
        ),
    },
    async ({ filter }) => {
      const entries = await fetchStorybookIndex();
      const filterLower = filter?.toLowerCase();

      // Group by title
      const groups: Record<string, string[]> = {};
      for (const entry of Object.values(entries)) {
        if (entry.type !== "story") continue;
        if (filterLower && !entry.title.toLowerCase().includes(filterLower) && !entry.name.toLowerCase().includes(filterLower)) continue;
        if (!groups[entry.title]) groups[entry.title] = [];
        groups[entry.title].push(entry.name);
      }

      const totalStories = Object.values(groups).reduce((s, v) => s + v.length, 0);
      const lines = [
        `# Backstage Storybook — ${totalStories} stories in ${Object.keys(groups).length} components`,
        `Source: ${STORYBOOK_INDEX_URL}\n`,
        filter ? `Filter: "${filter}"\n` : "",
        ...Object.entries(groups)
          .sort((a, b) => a[0].localeCompare(b[0]))
          .map(([title, stories]) => {
            const titleSlug = title.toLowerCase().replaceAll(/[^a-z0-9]/g, "-").replaceAll(/-+/g, "-");
            const storyLines = stories.map((s) => {
              const storySlug = s.toLowerCase().replaceAll(/[^a-z0-9]/g, "-").replaceAll(/-+/g, "-");
              return `  - ${s}  →  id: ${titleSlug}--${storySlug}`;
            });
            return `## ${title}\n${storyLines.join("\n")}`;
          }),
        "\nUse backstageui_storybook_get_story with the story ID to fetch source code and usage examples.",
      ];
      return textResult(lines.join("\n"));
    }
  );

  server.tool(
    "backstageui_storybook_get_story",
    "Get the source code (.stories.tsx) and component source (.tsx) for a specific Storybook story by ID (e.g. 'backstage-ui-accordion--default', 'backstage-ui-button--variants'). Use backstageui_storybook_list_stories to discover IDs.",
    {
      storyId: z
        .string()
        .describe(
          "Story ID from index.json (e.g. 'backstage-ui-accordion--default', 'backstage-ui-button--variants', 'data-display-table--default-table')"
        ),
    },
    async ({ storyId }) => {
      const entries = await fetchStorybookIndex();
      const entry = entries[storyId];
      if (!entry) {
        // Try fuzzy match
        const similar = Object.keys(entries)
          .filter((k) => k.includes(storyId.split("--")[0]))
          .slice(0, 5);
        const similarList = similar.map((s) => `- ${s}`).join("\n");
        return textResult(
          `Story not found: ${storyId}\n\nSimilar story IDs:\n${similarList}\n\nUse backstageui_storybook_list_stories to browse all stories.`
        );
      }

      const contents: string[] = [
        `# Storybook Story: ${entry.title} / ${entry.name}`,
        `ID: ${entry.id}`,
        `Story URL: https://backstage.io/storybook/?path=/story/${entry.id}`,
        `Export: ${entry.exportName ?? entry.name}`,
        `Source: github.com/${OWNER}/${REPO}/blob/${BRANCH}/${entry.importPath.replace("./", "")}`,
        "",
      ];

      // Fetch story source (.stories.tsx)
      const storyPath = entry.importPath.replace("./", "");
      try {
        const storySource = await fetchRaw(OWNER, REPO, storyPath, BRANCH);
        contents.push(`## Story Source (${storyPath.split("/").at(-1)})\n\`\`\`tsx\n${storySource}\n\`\`\``);
      } catch {
        contents.push(`(Could not fetch story source: ${storyPath})`);
      }

      // Fetch component source (.tsx)
      if (entry.componentPath) {
        const componentPath = entry.componentPath.replace("./", "");
        try {
          const componentSource = await fetchRaw(OWNER, REPO, componentPath, BRANCH);
          contents.push(`\n## Component Source (${componentPath.split("/").at(-1)})\n\`\`\`tsx\n${componentSource}\n\`\`\``);
        } catch {
          /* skip */
        }
      }

      return textResult(contents.join("\n"));
    }
  );

  server.tool(
    "backstageui_storybook_search",
    "Search Backstage Storybook stories by keyword — finds stories across all 643 stories by title, component name, or story name.",
    {
      query: z.string().describe("Search keyword (case-insensitive, e.g. 'table', 'button', 'search', 'dialog')"),
    },
    async ({ query }) => {
      const entries = await fetchStorybookIndex();
      const queryLower = query.toLowerCase();
      const matches = Object.values(entries)
        .filter(
          (e) =>
            e.type === "story" &&
            (e.title.toLowerCase().includes(queryLower) ||
              e.name.toLowerCase().includes(queryLower) ||
              e.id.toLowerCase().includes(queryLower))
        )
        .slice(0, 30);

      if (matches.length === 0) {
        return textResult(`No stories found matching "${query}" in Backstage Storybook.`);
      }

      const lines = [
        `# Storybook Search: "${query}" — ${matches.length} results\n`,
        ...matches.map(
          (e) =>
            `- **${e.title}** / ${e.name}\n  ID: \`${e.id}\`\n  URL: https://backstage.io/storybook/?path=/story/${e.id}`
        ),
      ];
      return textResult(lines.join("\n"));
    }
  );
}
