apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Aplicación Angular generada desde el golden path base (agnóstica, sin lógica de negocio)
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner }}
